# Generated by Django 5.2.6 on 2025-09-06 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('due_date', models.DateField()),
                ('due_time', models.TimeField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('compleated', 'complated')], default='pending', max_length=100)),
                ('category', models.CharField(choices=[('work', 'work'), ('personal', 'personal'), ('other', 'other')], max_length=100)),
                ('is_compleated', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
